### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by bobking256** [sansil/vt-notifications#4]
Is this working with Tailwindcss 2+?  The position is fixed at top right.  When trying to show more that one notification, only one appears.  Using Vue 2.x and Tailwindcss 2.x

**Comment by bobking256** [comment]
Resolve issue.

**Comment by realslimsutton** [comment]
@bobking256 Did you get this working? I'm attempting to change position to bottom but it doesn't appear to have any impact:

`<notificationGroup position="bottom">...</notificationGroup>`
